### ISSUE TITLE
SendDtmf and Pause BXML verbs not implemented

### ISSUE THREAD

**Issue by timr** [Bandwidth/java-bandwidth#47]
I noticed support for the [SendDtmf](https://dev.bandwidth.com/ap-docs/bxml/verbs/sendDtmf.html) and [Pause](https://dev.bandwidth.com/ap-docs/bxml/verbs/pause.html) BXML verbs are missing. Could those be added? Otherwise, I'm willing to submit what I've done.

 - Tim

**Comment by jmulford-bandwidth** [comment]
@timr Feel free to open up a PR with your updates

**Comment by timr** [comment]
Hi @jmulford-bandwidth,

I created a PR for review. Unfortunately, I wasn't able to add any reviewers to it.

https://github.com/Bandwidth/java-bandwidth/pull/48
